name: Build and release on push
on:
  push:
    tags:
      - '*'
defaults:
  run:
    shell: bash
    working-directory: ./ModTemplate
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Retrieve tag
        id: tag
        run: echo TAG_NAME="$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - uses: robinraju/release-downloader@v1.8
        with:
          repository: "Curtbot9000/SalemModLoader"
          latest: true
          fileName: "SalemModLoader.dll"
          out-file-path: "ModTemplate/libs"
      - run: |
              git config --global user.name 'VoidBehemoth'
              git config --global user.email 'voidbehemoth@gmail.com'
              git add "./libs/SalemModLoader.dll"
              git commit -am "Automatically download SalemModLoader"
              git archive -o "./SalemMod-${{ steps.tag.outputs.TAG_NAME }}.zip" HEAD
      - run: ls
      - uses: ncipollo/release-action@v1.13.0
        id: create_release
        with:
          artifactErrorsFailBuild: true
          artifacts: "./ModTemplate/SalemMod-${{ steps.tag.outputs.TAG_NAME }}.zip"
          body: "Fixed error where image caused VS to not fully load template.\n\nCompatible with TOS2 Patch R.1.1.37. Check README.md for more instructions."