name: Build and release on push
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ModTemplate
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Retrieve tag
        id: tag
        run: echo TAG_NAME="$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - run: git archive -o "./SalemMod-${{ steps.tag.outputs.TAG_NAME }}.zip" HEAD
      - run: |
            git config --global user.name 'VoidBehemoth'
            git config --global user.email 'voidbehemoth@gmail.com'
            git add "./SalemMod-${{ steps.tag.outputs.TAG_NAME }}.zip"
            git commit -am "Automated release."
      - uses: actions/checkout@v4.1.0
      - uses: ncipollo/release-action@v1.13.0
        id: create_release
        with:
          artifacts: "./ModTemplate/SalemMod-${{ steps.tag.outputs.TAG_NAME }}.zip"
          body: "Compatible with TOS2 Patch R.1.1.37. Check README.md for more instructions."