name: Build and release on push
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.0
      - run: cd ./ModTemplate/
      - name: Retrieve tag
        id: tag
        run: echo TAG_NAME="$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - run: mkdir ./../releases
      - run: git archive -o "./../releases/SalemMod-${{ steps.tag.outputs.TAG_NAME }}.zip" HEAD
      - uses: actions/checkout@v4.1.0
      - uses: ncipollo/release-action@v1.13.0
        id: create_release
        with:
          artifacts: "./../releases/SalemMod-${{ steps.tag.outputs.TAG_NAME }}.zip"
        